    "Ecuador": {"population": 18.2, "continent": "South America"},
    "Cambodia": {"population": 17.0, "continent": "Asia"},
    "Senegal": {"population": 18.2, "continent": "Africa"},
    "Chad": {"population": 18.8, "continent": "Africa"},
    "Somalia": {"population": 18.7, "continent": "Africa"},
    "Zimbabwe": {"population": 17.1, "continent": "Africa"},
    "Guinea": {"population": 14.5, "continent": "Africa"},
    "Rwanda": {"population": 14.4, "continent": "Africa"},
    "Benin": {"population": 14.1, "continent": "Africa"},
    "Burundi": {"population": 13.6, "continent": "Africa"},
    "Tunisia": {"population": 12.5, "continent": "Africa"},
    "Bolivia": {"population": 12.5, "continent": "South America"},
    "Belgium": {"population": 11.9, "continent": "Europe"},
    "Haiti": {"population": 11.9, "continent": "North America"},
    "Cuba": {"population": 11.0, "continent": "North America"},
    "South Sudan": {"population": 11.3, "continent": "Africa"},
    "Dominican Republic": {"population": 11.4, "continent": "North America"},
    "Czech Republic": {"population": 10.9, "continent": "Europe"},
    "Greece": {"population": 10.3, "continent": "Europe"},
    "Sweden": {"population": 10.6, "continent": "Europe"},
    "Portugal": {"population": 10.2, "continent": "Europe"},
    "Azerbaijan": {"population": 10.4, "continent": "Asia"},
    "Hungary": {"population": 9.6, "continent": "Europe"},
    "Honduras": {"population": 10.6, "continent": "North America"},
    "Israel": {"population": 9.9, "continent": "Asia"},
    "Tajikistan": {"population": 10.5, "continent": "Asia"},
    "Belarus": {"population": 9.1, "continent": "Europe"},
    "Austria": {"population": 9.1, "continent": "Europe"},
    "Switzerland": {"population": 8.9, "continent": "Europe"},
    "Papua New Guinea": {"population": 10.5, "continent": "Oceania"},
    "United Arab Emirates": {"population": 9.5, "continent": "Asia"},
    "Jordan": {"population": 11.4, "continent": "Asia"},
    "Serbia": {"population": 7.1, "continent": "Europe"},
    "Hong Kong": {"population": 7.5, "continent": "Asia"},
    "Libya": {"population": 7.0, "continent": "Africa"},
    "Bulgaria": {"population": 6.7, "continent": "Europe"},
    "Paraguay": {"population": 6.9, "continent": "South America"},
    "El Salvador": {"population": 6.4, "continent": "North America"},
    "Singapore": {"population": 6.1, "continent": "Asia"},
    "Denmark": {"population": 6.0, "continent": "Europe"},
    "Finland": {"population": 5.6, "continent": "Europe"},
    "Norway": {"population": 5.5, "continent": "Europe"},
    "Slovakia": {"population": 5.4, "continent": "Europe"},
    "Ireland": {"population": 5.3, "continent": "Europe"},
    "New Zealand": {"population": 5.3, "continent": "Oceania"},
    "Costa Rica": {"population": 5.2, "continent": "North America"},
    "Lebanon": {"population": 5.3, "continent": "Asia"},
    "Oman": {"population": 4.7, "continent": "Asia"},
    "Panama": {"population": 4.5, "continent": "North America"},
    "Kuwait": {"population": 4.3, "continent": "Asia"},